AWSTemplateFormatVersion: 2010-09-09
Description: CodeBuild project for continuous integration

# Note: It's necessary to set up the AWS OAuth application to have access to your repositories.
# To do it, navigate to the AWS CodeBuild console, create a project and select GitHub as source provider. The project does not need to be saved, it is only important to connect to GitHub. It only needs to be done once.

Parameters:
  GitUser:
    Type: String

  GitRepo:
    Type: String

  SubSystem:
    Type: String
    Description: Subsystem Code (should be all lowercases)
    AllowedPattern: "^[a-z]+$"

  ServiceName:
    Type: String

  SourcePath:
    Type: String

Resources:
  CodeBuildIAMRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Join ['-', [!Ref 'AWS::StackName', 'DeployCodeBuildRolePolicy']]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - ecs:*
                  - cloudwatch:*
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*

  CodeBuildDeploy:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ServiceName}-${SubSystem}-ecs-deploy
      Description: ECS Deployer
      ServiceRole: !GetAtt CodeBuildIAMRole.Arn
      Artifacts:
        Type: no_artifacts
      Source:
        Type: GITHUB
        Auth:
          Type: OAUTH
        Location: !Sub https://github.com/${GitUser}/${GitRepo}.git
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - COMMIT="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
                - WORKDIR=$(pwd)
                - echo "Current Git commit is ${COMMIT} at ${CODEBUILD_SOURCE_REPO_URL}"
            build:
              commands:
                - echo "Starting deployment for ${SERVICE_NAME} at ${COMMIT} in ${ENV_LABEL} environment..."
                - cd $SOURCE_PATH
                - make build
                - make test
                - make ecr-push
                - make update-service
      Triggers:
        Webhook: false
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:17.09.0
        EnvironmentVariables:
        - Name: SOURCE_PATH
          Value: !Ref SourcePath
        - Name: SERVICE_NAME
          Value: !Ref ServiceName
